#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : python-mistralclient
Version  : 2.0.0
Release  : 13
URL      : http://tarballs.openstack.org/python-mistralclient/python-mistralclient-2.0.0.tar.gz
Source0  : http://tarballs.openstack.org/python-mistralclient/python-mistralclient-2.0.0.tar.gz
Summary  : Mistral Client Library
Group    : Development/Tools
License  : Apache-2.0
Requires: python-mistralclient-bin
Requires: python-mistralclient-python
Requires: PyYAML
Requires: cliff
Requires: pbr
Requires: python-keystoneclient
Requires: python-openstackclient
Requires: requests
BuildRequires : configparser-python
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools
Patch1: 0001-test.patch

%description
Mistral client
==============
Python client for Mistral REST API. Includes python library for Mistral API and Command Line Interface (CLI) library.

%package bin
Summary: bin components for the python-mistralclient package.
Group: Binaries

%description bin
bin components for the python-mistralclient package.


%package python
Summary: python components for the python-mistralclient package.
Group: Default

%description python
python components for the python-mistralclient package.


%prep
%setup -q -n python-mistralclient-2.0.0
%patch1 -p1

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489334377
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1489334377
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mistral

%files python
%defattr(-,root,root,-)
/usr/lib/python*/*
