#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0xB9069B1335700CDC (infra-root@openstack.org)
#
Name     : python-mistralclient
Version  : 3.0.0
Release  : 15
URL      : http://tarballs.openstack.org/python-mistralclient/python-mistralclient-3.0.0.tar.gz
Source0  : http://tarballs.openstack.org/python-mistralclient/python-mistralclient-3.0.0.tar.gz
Source99 : http://tarballs.openstack.org/python-mistralclient/python-mistralclient-3.0.0.tar.gz.asc
Summary  : Mistral Client Library
Group    : Development/Tools
License  : Apache-2.0
Requires: python-mistralclient-bin
Requires: python-mistralclient-python
Requires: PyYAML
Requires: cliff
Requires: osc-lib
Requires: oslo.i18n
Requires: oslo.utils
Requires: pbr
Requires: python-keystoneclient
Requires: requests
Requires: six
Requires: stevedore
BuildRequires : pbr
BuildRequires : pip
BuildRequires : python-dev
BuildRequires : python3-dev
BuildRequires : setuptools

%description
========================
Team and repository tags
========================
.. image:: http://governance.openstack.org/badges/python-mistralclient.svg
:target: http://governance.openstack.org/reference/tags/index.html

%package bin
Summary: bin components for the python-mistralclient package.
Group: Binaries

%description bin
bin components for the python-mistralclient package.


%package python
Summary: python components for the python-mistralclient package.
Group: Default

%description python
python components for the python-mistralclient package.


%prep
%setup -q -n python-mistralclient-3.0.0

%build
export LANG=C
export SOURCE_DATE_EPOCH=1489856029
python2 setup.py build -b py2
python3 setup.py build -b py3

%install
export SOURCE_DATE_EPOCH=1489856029
rm -rf %{buildroot}
python2 -tt setup.py build -b py2 install --root=%{buildroot} --force
python3 -tt setup.py build -b py3 install --root=%{buildroot} --force

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/mistral

%files python
%defattr(-,root,root,-)
/usr/lib/python2*/*
/usr/lib/python3*/*
